# Generated by Django 4.2.3 on 2023-08-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('rating', models.CharField(max_length=30)),
                ('catagory', models.CharField(max_length=30)),
            ],
        ),
    ]
